
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mymxckrsiiasuihqkyan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bXhja3JzaWlhc3VpaHFreWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5OTIzNjEsImV4cCI6MjA1NzU2ODM2MX0.SeRryg_5wYafqo0s6xLD15-nzs4XX_JN0kVICYwtwUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
